version: "3.7"

services:
  frontend:
    container_name: startrip
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development